import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "./components/AppSidebar";
import { HomeNavbar } from "./components/HomeNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}
      >
        <div
          className="max-w-[1480px] w-full flex justify-center h-full"
          style={{ margin: "0 auto" }}
        >
          {/* <Header /> */}
          <section className="grow-2 h-screen flex hidden md:block flex-shrink-0 relative">
            <AppSidebar />
          </section>
          <section className="grow-9 h-screen border-x-1 overflow-y-scroll">
            <HomeNavbar />
            {children}
            {/* following */}
            {/* recommended */}
          </section>
          <section className="grow-2 h-screen hidden md:block flex-shrink-0">
            <p>aaaaaaaaaaaaaaaaaaaaa</p>
          </section>
        </div>
      </body>
    </html>
  );
}
